# Generated by Django 3.2.7 on 2021-10-04 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('releaseDate', models.DateField()),
                ('synopsis', models.TextField()),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='core.director')),
                ('genre', models.ManyToManyField(related_name='movies', to='core.Genre')),
            ],
        ),
    ]
