# Generated by Django 3.2.7 on 2021-10-08 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movietime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Dubbed'), (1, 'Subtitled')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0)),
                ('price', models.FloatField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='core.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='core.movie')),
                ('movieTime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='core.movietime')),
            ],
        ),
    ]
